### ISSUE TITLE
changing password via /v1/reset-password resulting unexpected behaviour

### ISSUE THREAD

**Issue by Rakemoon** [ptrjs/express-reserve-app#14]
# Cara Melakukan
- Buat http request post ke /v1/forgot-password
- Dapat token dri email
- coba membuat http request post ke /v1/reset-password dengan query token dan body password
# Hasil yang didapat
Response 200 (OK) namun ketika melihat pada table yang diubah bukan lah user yang dituju melainkan user yang lain
dan password yang disimpan tidak di hash terlebih dahulu, sehingga mengakibatkan salah password  terus ketika user login

**Comment by Rakemoon** [comment]
Duplicate of #13

**Comment by ptrjs** [comment]
Masalahnya ada di user.service.js.

### Code yang diubah
```
const getUserById = async (id) => {
  console.log(Fetching user with id: ${id});
  return prisma.user.findUnique({
    where: {
      id,
    },
  });
};

```
### Code sebelumnya 
Pada code sebelumnya menggunakan method findFirst sehingga function getUserById mengambil data pertama user di dalam database. Akibatnya user dengan urutan 1 yang terimpact.
