### ISSUE TITLE
issue login ketika user data tidak ada dalam database

### ISSUE THREAD

**Issue by Rakemoon** [ptrjs/express-reserve-app#3]
# Cara melakukan
- membuat post request ke `/v1/auth/login` dan isi mengisi form nya

# Respons
- Internal Server Error 500

# Respon yang diharapkan
- membuat respons bahwa user tidak terdaftar dan harus regristrasi terlebih dahulu

**Comment by ptrjs** [comment]
siap sir, mungkin agak malaman ntar saya kerjakan

**Comment by ptrjs** [comment]
seperti ini kan sir

`const loginUserWithEmailAndPassword = async (email, password) => {
  const user = await userService.getUserByEmail(email);
  if (!user) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User not registered. Please register first.');
  }
  const validPassword = await bcrypt.compare(password, user.password);

  if (!user || !validPassword) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'Incorrect email or password');
  }
  return user;
};`
